### ISSUE TITLE
Filtering for quality gives strange results

### ISSUE THREAD

**Issue by JannikaSchaefer** [3dgeo-heidelberg/pytreedb#100]
I expected adding more quality levels would result in more trees found, but the opposite happens. I think this is wrong.

Species: Pinus sylvestris
Mode: ULS
Quality: 1
=> 6 Trees found

Species: Pinus sylvestris
Mode: ULS
Quality: 1 2
=> 5 Trees found

Species: Pinus sylvestris
Mode: ULS
Quality: 1 2 3
=> 2 Trees found

**Comment by bhoefle-3dgeo** [comment]
Solved with commit 9ae02a00215ba3a2130f47fbc7fa64b80325cc5b
