### ISSUE TITLE
Linking conditions is not always working

### ISSUE THREAD

**Issue by JannikaSchaefer** [3dgeo-heidelberg/pytreedb#115]
I cannot find a way to filter for trees which have a leaf-off ALS point cloud (there should not be any). 
("mode:ALS" AND "canopy_condition:Leaf-off") will result in all trees for which an ALS point cloud and any leaf-off point cloud is available.

**Comment by han16nah** [comment]
Did you try with enabling the "All search criteria should be fulfilled by a single data source" checkbox?

**Comment by JannikaSchaefer** [comment]
No, I did not. I didn't see the checkbock. It's working now.

**Comment by han16nah** [comment]
thank god 😅
