### ISSUE TITLE
package data for download

### ISSUE THREAD

**Issue by lwiniwar** [3dgeo-heidelberg/pytreedb#2]
since we want to allow users to download all fitting trees at once, we need a function to create a zip file with the data.

This should be similar to the process described in #1 :

*POST* (list of tree model ids and data type (ULS, ALS, voxel model,...)) -> `/package_data`
  - Returns ID of temporary endpoint `/packaging/abc123`

*GET* () ->  `/packaging/abc123` 
  - Returns progress (`{id: 'abc123', progress: 'creating zip file'}`

*GET* () -> `/packaging/abc123` (after finishing)
  - Returns link to download (`{id: 'abc123', progress: 'Finished', download_url: '/packaging/abc123/download.zip'}`

**Comment by bhoefle-3dgeo** [comment]
See #42.
