### ISSUE TITLE
Add documentation in subfolder webserver [REPLACEMENT ISSUE]

### ISSUE THREAD

**Issue by lwiniwar** [3dgeo-heidelberg/pytreedb#31]
The original issue

	Id: 18
	Title: Add documentation in subfolder webserver

could not be created.
This is a dummy issue, replacing the original one.In case the gitlab repository still exists, visit the following link to see the original issue:

https://gitlab.gistools.geog.uni-heidelberg.de/giscience/3DGeo/pytreedb/-/issues/18

**Comment by annachiu7** [comment]
Can we close this now?

**Comment by bhoefle-3dgeo** [comment]
Re-check if all infos are available. Still room for improvement.

**Comment by bhoefle-3dgeo** [comment]
@lwiniwar can we close it? All info provided?

**Comment by lwiniwar** [comment]
jup, I'm happy. Thanks!
