### ISSUE TITLE
Webfrontend: Clicking on map icon should show tree information [REPLACEMENT ISSUE]

### ISSUE THREAD

**Issue by lwiniwar** [3dgeo-heidelberg/pytreedb#35]
The original issue

	Id: 28
	Title: Webfrontend: Clicking on map icon should show tree information

could not be created.
This is a dummy issue, replacing the original one.In case the gitlab repository still exists, visit the following link to see the original issue:

https://gitlab.gistools.geog.uni-heidelberg.de/giscience/3DGeo/pytreedb/-/issues/28

**Comment by bhoefle-3dgeo** [comment]
Pop up incl. id, species and URL (via API) to full GeoJSON

**Comment by annachiu7** [comment]
Solved in commit 6303fa9. But only the tree ID is shown in the popup (of course it links to the json file), because the name already has the species abbrev in it
