### ISSUE TITLE
Webfrontend: Removed/Old filters are still applied [REPLACEMENT ISSUE]

### ISSUE THREAD

**Issue by lwiniwar** [3dgeo-heidelberg/pytreedb#36]
The original issue

	Id: 30
	Title: Webfrontend: Removed/Old filters are still applied

could not be created.
This is a dummy issue, replacing the original one.In case the gitlab repository still exists, visit the following link to see the original issue:

https://gitlab.gistools.geog.uni-heidelberg.de/giscience/3DGeo/pytreedb/-/issues/30

**Comment by annachiu7** [comment]
This issue originates from the same problem as #37
