### ISSUE TITLE
Write tests for the pytreedb-server API

### ISSUE THREAD

**Issue by lwiniwar** [3dgeo-heidelberg/pytreedb#44]
We should write some tests to check the functionality of the HTTP API, covering all endpoints:

`/search` [POST]

`/search/wssearch` [POST]

`/search/exportcollection` [POST]

`/search/lazlinks` [POST]

`/expotcsv` [POST]

`/query`

`/stats`

`/listspecies`

`/getitem`

`/sharedproperties`

**Comment by annachiu7** [comment]
I'm still changing the routings right now *sweat*

**Comment by lwiniwar** [comment]
tests have been added on the [api-tests](https://github.com/3dgeo-heidelberg/pytreedb/tree/api-tests) branch. @annachiu7 , please update the three last tests, currently they return empty results and I don't know what is expected from the client - there have been API changes recently.
You could tests for number of returned elements, a single link (string equality), ...

**Comment by lwiniwar** [comment]
Here are the corresponding lines:
https://github.com/3dgeo-heidelberg/pytreedb/blob/d2729b87e1995f27b6790ab328bf496dbd304c7e/webserver/pytreedb_server/test/test_api.py#L114-L133

**Comment by annachiu7** [comment]
Updated in 4f0addd

**Comment by lwiniwar** [comment]
thanks!
