### ISSUE TITLE
Set up production webserver / API for showcase

### ISSUE THREAD

**Issue by bhoefle-3dgeo** [3dgeo-heidelberg/pytreedb#46]
Implement API on syssifoss server in a production mode (via Apache etc.) to have a running instance as example server for users to test and work with the datasets from the SYSSIFOSS project.

Targeted endpoint: http://syssifoss.geog.uni-heidelberg.de/pytreedb

- [x] Install API on syssifoss server and modify server settings. FLASK instance can remain as example for simple API on current end point.
- [x] Modify all example scripts and Notebooks to use this new API entry point
- [x] Use this in the API tests

**Comment by bhoefle-3dgeo** [comment]
Please check this one.

**Comment by lwiniwar** [comment]
Endpoint was changed to http://pytreedb.geog.uni-heidelberg.de/
- This is only relevant in the API examples, i.e. the R script. Here, it was already adapted:

https://github.com/3dgeo-heidelberg/pytreedb/blob/ce5475547f71b65b628d7a2284f1c9a287e0ee45/examples_api/example.R#L38

- To work in the tests, we would need to expose the webserver to the public. Currently, it is only accessible from within Uni HD or KIT. Before doing so, I would opt for a nicer landing page on [http://syssifoss.geog.uni-heidelberg.de](http://syssifoss.geog.uni-heidelberg.de/pytreedb) (and removal of the phpinfo and database access). Any info that should be included on the syssifoss landing page?

**Comment by lwiniwar** [comment]
API tests are connected to #44. @annachiu7 are the endpoints finalized?

**Comment by annachiu7** [comment]
> API tests are connected to #44. @annachiu7 are the endpoints finalized?

Not yet. I'll still have to work on the downloading aspect next week

**Comment by annachiu7** [comment]
> API tests are connected to #44. @annachiu7 are the endpoints finalized?

@lwiniwar I changed 3 endpoints on the branch huge_dl and the pull request is here #53

**Comment by lwiniwar** [comment]
API tests now use
(a) local mongodb, local flask server
(b) cloud mongodb, local flask server
(c) cloud mongodb, pytreedb.geog.uni-heidelberg.de server

(see [d2729b8](https://github.com/3dgeo-heidelberg/pytreedb/commit/d2729b87e1995f27b6790ab328bf496dbd304c7e))
