### ISSUE TITLE
Frontend queries - Idea for improvement (`$elemMatch`)

### ISSUE THREAD

**Issue by han16nah** [3dgeo-heidelberg/pytreedb#52]
In the Frontend, we combine multiple conditions with `OR` / `AND`. These includes queries on data fields, which are present multiple times for one tree (e.g. canopy condition or tree metrics like Height). There are two options:

- Currently implemented, conditions are fulfilled by the data/measurement elements of one DB entry but potentially not by exactly the same element. Example: We search for a tree measured by TLS and measured in leaf-off conditions. Even though we do not have any trees with TLS leaf-off point clouds, we get results, because we have trees measured by TLS and by ULS leaf-off.
- To be implemented additionally (??), all conditions are fulfilled by one single data/measurement element of the DB entry. For the example above, this would mean that we query for a tree that has a point cloud which was acquired in leaf-off conditions by TLS (ULS leaf-off measurements would not fulfill the query).

This can be done using the `$elemMatch` operator (https://www.mongodb.com/docs/manual/reference/operator/query/elemMatch/). 
>The [$elemMatch](https://www.mongodb.com/docs/manual/reference/operator/query/elemMatch/#mongodb-query-op.-elemMatch) operator matches documents that contain an array field with at least one element that matches all the specified query criteria.

You can check [07_query_with_multiple_conditions.ipynb](https://github.com/3dgeo-heidelberg/pytreedb/blob/main/notebooks/07_query_with_multiple_conditions.ipynb) for examples of queries with `$elemMatch`

I am not sure yet how this could look like in the user interface. Maybe there could be a checkbox next to the filter for which `elemMatch` should apply?

**Comment by bhoefle-3dgeo** [comment]
@annachiu7, I think this is an important aspect of the query tool in the web frontend. @han16nah elemMatch is might be not a good word for non-Mongo-users. We could add a check box to force that all search criteria are fullfilled for a data/measurement element and hint with a "?" link to the notebook and the elemMatch issue.

**Comment by annachiu7** [comment]
This is updated in the latest commit of frontend_query_enhance branch. Needs testing

**Comment by han16nah** [comment]
@annachiu7 Is it only possible atm to connect ALL filters with elemMatch (with the checkbox "All search criteria should be fulfilled by a single data source")?
Would it also be feasible to connect it somehow to the "Source" and "Mode" filters (as these are the filters which we would like to conntect elemMatch to").. Maybe with checkboxes  saying "indented search criteria below should be fulfilled by a single data source/acquisition mode" - and whenever I add another mode/source filter, another checkbox appears?

Then I could e.g. specify that I need a TLS point cloud in leaf-on condition with quality 3 or better or alternatively a ULS point cloud in leaf-off condition with quality 2 or better..

**Comment by han16nah** [comment]
@annachiu7 Can the frontend_query_enhance branch we merged?
