### ISSUE TITLE
Webfrontend: download of files

### ISSUE THREAD

**Issue by bhoefle-3dgeo** [3dgeo-heidelberg/pytreedb#55]
Please add file prompt for all downloads such that the user can choose where and how to name the download of files.

**Comment by annachiu7** [comment]
Users are already always able to choose the download location and are able to change the file name. The "open/save as" prompt is a part of browser settings, and the frontend has nothing to do about it.

**Comment by bhoefle-3dgeo** [comment]
I thought that with defining content disposition you can say that it is an attachment. This is what I can remember slightly from PHP times long ago but might me more related to server-side issues.
 Of course, you cannot control browser behaviour but support downloading. I think in HTML5 you can also specify the **download attribute for hyperlinks**: [](https://www.w3schools.com/howto/howto_html_download_link.asp). Please add those - if applicable.

**Comment by annachiu7** [comment]
Ok, I just added the download attributes in commit ed97599. 
And yes, I also looked into content disposition. I am already working on improving the flask responses if files are directly provided for download (if frontend doesn't need to read/edit them beforehand)

**Comment by annachiu7** [comment]
I think we can close this now?

**Comment by bhoefle-3dgeo** [comment]
- [ ] When clicking on Button "Point Clouds" the small window opens and there is a button "Close" and "Save Changes". The "Save Changes" button is not doing anything and not needed if I am right.

- [ ] In the Python download script, there should be the standard option to support sys.arg for input file and output_directory instead of hardcoding. furthermore, the path handling in the code needs to be improved. instead of string tricks, use the Path module of Python. Furthermore, add error handling if input file cannot be read or output directory not accessible. 


After that I think we can close it and reopen in case of further problems.
