### ISSUE TITLE
Webserver: cross-origin-request permit not given by 3dweb.geog.uni-heidelberg.de

### ISSUE THREAD

**Issue by annachiu7** [3dgeo-heidelberg/pytreedb#60]
The point cloud .laz files are on 3dweb.geog.uni-heidelberg.de, but it doesn't have CORS permit for http://pytreedb.geog.uni-heidelberg.de/ (=> ajax get request error). Please add CORS headers

**Comment by lwiniwar** [comment]
not required as no CORS requests are implemented.
