### ISSUE TITLE
Webfrontend: Select by map extent jumps

### ISSUE THREAD

**Issue by bhoefle-3dgeo** [3dgeo-heidelberg/pytreedb#67]
The new and cool function "select by map extent" somehow alters the extent and it appears that it moves and even zooms out a little bit. the exact current map extent should be used and should stay when clicking on the button. 
Is it a coordinate rounding issue?

**Comment by annachiu7** [comment]
I'm not sure how to replicate this issue. Actually, the exact bounds are sent to backend for geometric query with an accuracy of 15 decimal points. I think the appearance of extent altering comes from the new query - although the trees in these bounds are still the same, but the map is refreshed to better display those trees.

**Comment by bhoefle-3dgeo** [comment]
You can replicate it by zooming in to a bunch of trees and then press "Select by map extent" multiple times. Then it will change the map view extent and also add trees. Actually it should stay the same map extent and also the trees shown in the map extent should be the ones that are selected by this operation.

Could it be that by using "pan" on the map view, the trees are not reloaded and this might cause this effect. This could explain that more trees appear in the map view but not that the map extent is changed. 

Is there a divergence between map view and map boundary in this library?
