### ISSUE TITLE
Webfrontend: Add pytreedb logo

### ISSUE THREAD

**Issue by bhoefle-3dgeo** [3dgeo-heidelberg/pytreedb#71]
Please add official pytreedb logo to web portal main page and relevant sub-pages. Logo is here: [https://github.com/3dgeo-heidelberg/pytreedb/blob/main/pytreedb_logo_low.png](https://github.com/3dgeo-heidelberg/pytreedb/blob/main/pytreedb_logo_low.png)

**Comment by annachiu7** [comment]
Is there anywhere else the logo should be replaced?

**Comment by bhoefle-3dgeo** [comment]
Check yourself. Thanks.
