### ISSUE TITLE
Write tests (using pytests) to verify the code/library is running correclty

### ISSUE THREAD

**Issue by lwiniwar** [3dgeo-heidelberg/pytreedb#8]
In GitLab by @bhoefle-3dgeo on Dec 13, 2021, 15:35

See pytests example from HELIOS++: [https://github.com/3dgeo-heidelberg/helios/blob/dev/pytests/test_demo_scenes.py](https://github.com/3dgeo-heidelberg/helios/blob/dev/pytests/test_demo_scenes.py)

**Comment by bhoefle-3dgeo** [comment]
@han16nah : Can this be closed?

**Comment by han16nah** [comment]
I think we have a good test suite now which covers most of the pytreedb functionality :) 

Whenever we implement a new function or find & fix a bug, we should write a test for it as well :)
