### ISSUE TITLE
Select by map extent - Feedback to User

### ISSUE THREAD

**Issue by han16nah** [3dgeo-heidelberg/pytreedb#92]
We should add a feature that gives feedback to the user after clicking "select by map extent". Options could be:
- the preview window on the left is updated with the selected objects. The message could e.g. change to: XX trees found, YY trees selected.
- the markers of selected trees in the map could change their color.
- the selection in the map shortly changes color or a frame appears or some other "screenshot-like" behaviour that gives the user feedback, that the selection was updated. 

Further question:
Shall we rename the buttons to `Save JSON`, `Save selected to JSON`, `Export selected to CSV`, `Save selected point clouds`? I think this would be clearer than the current naming.  And add (JSON) to the `Download all data` button?

**Comment by annachiu7** [comment]
Option one is implemented now in the frontend branch

**Comment by annachiu7** [comment]
Tooltips added for button for more clarity in frontend branch
